
// Navbar show on scroll
var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
var currentScrollPos = window.pageYOffset;
  if (prevScrollpos > currentScrollPos) {
    document.getElementById("navbar").style.top = "0";
  } else {
    document.getElementById("navbar").style.top = "-50px";
  }
  prevScrollpos = currentScrollPos;
}

let year = new Date().getFullYear()
let currentYear = document.getElementById("currentYear")
currentYear.innerHTML = year;

// Enable Popovers
$(function () {
  $('[data-toggle="popover"]').popover()
})

$('.popover-dismiss').popover({
  trigger: 'focus'
})

// Form handling
const form = document.getElementById("form");
const name = document.getElementById("name");
const email = document.getElementById("email");
const message = document.getElementById("message");

//Show input error message
function showError(input, message) {
  const validation = input.parentElement;
  validation.className = "error";
  const small = validation.querySelector("small");
  small.innerText = message;
}

// Show success outline
function showSuccess(input) {
  const validation = input.parentElement;
  validation.className = "success";
}

// Check email is valid
function checkEmail(input) {
  const regex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  if (regex.test(input.value.trim())) {
    showSuccess(input);
  } else {
    showError(input, "Email is not valid");
  }
}

//Check required fields
function checkRequired(inputArr) {
  inputArr.forEach(input => {
    if (input.value.trim() === "") {
      showError(input, `${getFieldName(input)} is required`);
    } else {
      showSuccess(input);
    }
  });
}


// Check input Length
function checkLength(input, min) {
  if (input.value.length < min) {
    showError(
      input,
      `${getFieldName(input)} must be at least ${min} characters`
    );
  } 
}

// Get fieldname
function getFieldName(input) {
  return input.id.charAt(0).toUpperCase() + input.id.slice(1);
}

form.addEventListener("submit", function (e) {
  e.preventDefault();
  checkRequired([name, email, message]);
  checkLength(message, 3);
  checkEmail(email);
});


// Toast
let toastMessage = document.getElementById("toastMessage")
let toastTime = document.getElementById("toastTime")
let messageList = [
  {message: "Did you know? Over 3 million dollars were transactioned by businesses using our technology just this month!", time: "7 mins ago"},
  {message: "Did you know? We just hit 1.000.000 users! Thank you for your support!", time: "3 mins ago"},
  {message: "Did you know? This little message was generated by a customized JavaScript and not just the Bootstrap standard procedures, but I promise this is the last one ;)", time: "Just now"}
]
let i = 0
let delay = 2000

$(document).ready(function toast() {
  setTimeout(() => {
    toastTime.innerHTML = messageList[i].time;
    toastMessage.innerHTML = messageList[i].message;
    $(".toast").toast("show"); 
    i++;
    delay = 8000;
    if (i >= messageList.length) {
        return;
    } else {
      toast();
    }
  }, delay)
  })

// Floating iPhone
const iphoneFloating = document.getElementById("iphoneFloating");
const shadowFloating = document.getElementById("shadowFloating");
const touchArea = document.getElementById("touchArea")
let eventCount = 0

touchArea.addEventListener("touchstart", () => {
  if (eventCount == 0) {
    float();
    eventCount++;
  } else {
    unfloat();
    eventCount = 0;
  }
})

function float() {
  iphoneFloating.classList.remove("change-position");
  shadowFloating.classList.remove("change-position-shadow");
  iphoneFloating.classList.add("change-back");
  shadowFloating.classList.add("change-back-shadow");
  setTimeout(() => {
  iphoneFloating.classList.remove("change-back");
  shadowFloating.classList.remove("change-back-shadow");
  iphoneFloating.classList.add("floating");
  shadowFloating.classList.add("floating-shadow");
 }, 3000)
  
}

function unfloat() {
  iphoneFloating.classList.remove("change-back");
  shadowFloating.classList.remove("change-back-shadow");
  iphoneFloating.classList.add("change-position");
  shadowFloating.classList.add("change-position-shadow");
  iphoneFloating.classList.remove("floating");
  shadowFloating.classList.remove("floating-shadow");
}

document.addEventListener("DOMContentLoaded", float())

// AOS library
AOS.init({
  easing: 'ease-in-quad',
});
